general:
steps:
  mtaBuild:
    buildTarget: 'CF'
cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'ef01b822trial'
      space: 'HariDeploy'
      credentialsId: 'CF_CREDENTIALSID'
